-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- PROFILES TABLE
-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,
  
  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- MESSAGES TABLE
create table messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  content text not null,
  user_id uuid references auth.users not null,
  group_id bigint -- Optional, for group chats
);

alter table messages enable row level security;

create policy "Everyone can read messages"
  on messages for select
  using ( true );

create policy "Authenticated users can insert messages"
  on messages for insert
  with check ( auth.role() = 'authenticated' );

-- GROUPS TABLE
create table groups (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  created_by uuid references auth.users not null
);

alter table groups enable row level security;

create policy "Groups are viewable by everyone"
  on groups for select
  using ( true );

create policy "Authenticated users can create groups"
  on groups for insert
  with check ( auth.role() = 'authenticated' );

-- GROUP MEMBERS TABLE
create table group_members (
  id bigint generated by default as identity primary key,
  group_id bigint references groups on delete cascade not null,
  user_id uuid references auth.users not null,
  role text default 'member', -- 'admin', 'member'
  joined_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(group_id, user_id)
);

alter table group_members enable row level security;

create policy "Group members are viewable by everyone"
  on group_members for select
  using ( true );

create policy "Authenticated users can join groups"
  on group_members for insert
  with check ( auth.role() = 'authenticated' );

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url, username)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url', new.raw_user_meta_data->>'username');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to call the function on new user creation
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
